### PR TITLE
Remove copyrighted music

### PR DESCRIPTION
**Pull request by wish13yt**

### CODE REVIEW

**Comment by wish13yt** [comment]
it also adds a 404 screen

**Comment by wish13yt** [comment]
It also adds Discord embed support!

**Comment by wish13yt** [comment]
@5quirre1

**Comment by wish13yt** [comment]
@5quirre1 Please approve this. I would like the music gallery to shut down right now.
I am currently making a legal alternative to this with Spotify HTML embeds

**Comment by wish13yt** [comment]
The legal alternative is done!

**Comment by 5quirre1** [comment]
man
grge

**Pull request merged**
